CC = gcc
CFLAGS = -Wall -I "../../debugging" -I "../../rawIO14" -I "../../sofs14"
IFUNCS1 = soAllocInode.o soFreeInode.o soAllocDataCluster.o soFreeDataCluster.o

all:			ifuncs1

ifuncs1:		$(IFUNCS1)
