all32:
			make -C debugging all
			make -C rawIO14 all
			make -C sofs14 all
#			make -C syscalls14 all
			make -C showBlock14 all32
			make -C mkfs14 all32
#			make -C testifuncs14 all32
#			make -C mount14 all32

all64:
			make -C debugging all
			make -C rawIO14 all
			make -C sofs14 all
#			make -C syscalls14 all
			make -C showBlock14 all64
			make -C mkfs14 all64
#			make -C testifuncs14 all64
#			make -C mount14 all64

clean:
			make -C debugging clean
			make -C rawIO14 clean
			make -C sofs14 clean
#			make -C syscalls14 clean
			make -C showBlock14 clean
			make -C mkfs14 clean
#			make -C testifuncs14 clean
#			make -C mount14 clean
